### ISSUE TITLE
File keys generation not standard with other Storj clients

### ISSUE THREAD

**Issue by prestwich** [Storj/storj.js#13]
The code [here](https://github.com/Storj/storj.js/blob/NewAPI/lib/core/file.js#L167) doesn't seem to match up with the documentation [here](https://github.com/Storj/core/blob/master/doc/file-encryption.md).

Expected Behavior:
Generate a deterministic key from a Mnemonic and a file ID.

Actual Behavior:
Generate a deterministic key from a private signing key and a file ID.

**Comment by prestwich** [comment]
This is all tied up with the difficulty of persistence in browsers. More noodling below.

Use cases:
1. In-browser, no app server (e.g. storj.pics)
2. In-browser, w/ app server (e.g. video streaming service)
3. Non-browser apps (e.g. dropbox clone)

Case 3 is kinda trivial: it can persist the mnemonic locally. So the problem is confined to Cases 1&2. Case 2 can allow the app server to facilitate moving the mnemonic somehow. Case 1 can't.

So Case 1 will pretty much always require the user to input a mnemonic to interact with non-public files. Case 2's behavior will depend on the app, and that's okay.

I think the correct approach is accepting the mnemonic (or a file key) as an argument to anything requiring it, and letting apps figure out how exactly it gets there.

**Comment by retrohacker** [comment]
We ended up talking about this on slack. `createFile` should now handle keys properly: https://github.com/Storj/storj.js/blob/NewAPI/lib/api/createFile.js#L52-L69

**Comment by retrohacker** [comment]
The final API pushes key management and mnemonic management out to userland. You are required to supply the constructor your key and mnemonic if you want to be able to authenticate against bridge and encrypt/decrypt files.
