### ISSUE TITLE
Storj `ready` event not being emitted

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#23]
The documentation calls for a `ready` event to be emitted off of the Storj object during setup.

Currently there isn't any async setup necessary. In the original design of this API, there was a round trip for auth validation during setup. We decided to keep the async constructor for forward support of async operations during setup.

We can either:

A) drop the `ready` event and risk having to make a breaking change in the future
B) implement the `ready` event

I'm :+1: on (B)

**Comment by retrohacker** [comment]
This ended up being another bug. If neither `basicAuth` nor `keyPair` were provided, `self._client` wouldn't get instantiated and `ready` would not fire. Fixing in the `makePublic` PR.

**Comment by nginnever** [comment]
Also fixed here.

https://github.com/nginnever/storj.js/blob/webcrypto/lib/index.js#L86-L96

**Comment by retrohacker** [comment]
Nice. We did something similar but we support a constructor with all 3. Not sure why I treated them as separate cases originally.
