### ISSUE TITLE
UMD bundle exported as storj

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#76]
We are exporting the browserified bundle as `storj` as opposed to `Storj`

Per the browserify documentation, it looks like the `-s` flag will automagically be camel cased, so switching to `-s Storj` may not be enough to properly export the constructor.

**Comment by barbaraliau** [comment]
This is my bad. I would mark this as resolved. The bundle is correctly exported as `Storj`, but if using Webpack with a strict linter specifying `no-undef`, `Storj` will not be available globally by the time the linter runs. Solution is to tell the linter to chill out with:

```
/* global Storj */
/* eslint no-undef: ["error", { "typeof": false }] */
```

🙃
