### ISSUE TITLE
Browserified Library Not Defined

### ISSUE THREAD

**Issue by jake-walker** [Storj/storj.js#8]
I've made a browserified version of Storj.js using:
```
browserify lib/ -o storj.js
```
and when including it into the HTML like this:
```
<script src="storj.js"></script>
```
I get this error:
```
Uncaught ReferenceError: Storj is not defined
    at index.html:68
```
Here is the layout of my files:
```
storj-client
    |-- index.html
    `-- storj.js
```
Am I doing anything wrong or does it just not work?

**Comment by retrohacker** [comment]
Hey jake, nope this is a bug that was introduced a few commits back. Fixing now.

**Comment by retrohacker** [comment]
@jake-walker try rebuilding and let us know what mileage you get. Thanks for trying this library out in its early stages!

**Comment by jake-walker** [comment]
Sure! Thanks a lot.

**Comment by jake-walker** [comment]
It didn't work. I'm still getting the error about it not being defined. @retrohacker

**Comment by retrohacker** [comment]
Oh noes, that is strange.

If everything is working correctly `window.Storj` should be defined [here](https://github.com/Storj/storj.js/blob/NewAPI/lib/browser.js#L5) which is the entrypoint for [browserify](https://github.com/Storj/storj.js/blob/NewAPI/package.json#L8).

If possible, could you add a `console.log(self)` right after line 5 in `browser.js`, rerun `npm run build` and load in a browser? Would like to see the output in console.

**Comment by jake-walker** [comment]
Ah, I browserified the wrong file. It seems to be working alright now. Thanks for the help!
