### ISSUE TITLE
Fix errors in README.MD

### ISSUE THREAD

**Issue by QzSG** [Storj/storj.js#80]
Note this particular portion in readme.md
---
### `var stream = storj.download(fileId, bucketId)`

Return a readable stream of decrypted data being pulled directly from farmers. This method bypasses the File API entirely, and doesn't use a backend abstract-blob-store. If you only need to download a file once, and don't want to hold onto it in memory, this is the method for you.

```js
storj.download(fileId, bucketId).pipe(fs.createWriteStream('cat.jpg'));
```

The correct function should be `storj.download(bucketId,fileId)`

Will someone with access fix it, too small for me to file a pull request

**Comment by nginnever** [comment]
Thank you for pointing this out. I'm going to go ahead and just commit this on an open PR that I currently have.

https://github.com/Storj/storj.js/commit/11d7c2050f558464378f2a1cd5b16d802905fd22
